### ISSUE TITLE
How is this different from window-role="caption"?

### ISSUE THREAD

**Issue by GirkovArpa** [MustafaHi/Sciter-MovableView#1]
I can drag the window with a button like this:
```html
<button window-role="caption">Drag</button>
```
So I am interested in what advantage the technique presented in this repo has over the built-in way.

**Comment by MustafaHi** [comment]
```html
<caption role="window-caption">Heelo</caption>

**Comment by MustafaHi** [comment]
```html
*<button role="window-caption">Drag</button>
```

Mainly two features I needed.
1. It cheats Windows performance setting, when you drag the app window it will show as is, not just a frame.

2. It lacks window snapping, when you drag the app window to screen edge it won't snap to fit, suitable for fixed width applications or widgets.

**Comment by GirkovArpa** [comment]
Thanks for the typo correction. I am new to Sciter, and still don't have much memorized.

1. Isn't this customizable in Windows and enabled by default?  There's a tutorial on how to toggle this setting [here](https://www.tenforums.com/tutorials/27449-turn-off-show-window-contents-while-dragging-windows-10-a.html).  Do you want to override the user's preferences? 🤔

2.  Window snapping can be disabled with:
```html
<html window-resizable="false">
```

**Comment by MustafaHi** [comment]
>1. Do you want to override the user's preferences?

Yes.

> 2. Window snapping can be disabled with:
> ```html
> <html window-resizable="false">
> ```

Didn't know that.

**Comment by GirkovArpa** [comment]
The good thing about this is unlike `role="window-caption"`, it doesn't interfere with CSS cursor styles.
